### ISSUE TITLE
DNS because of musl/Alpine base?

### ISSUE THREAD

**Issue by guettli** [nicolaka/netshoot#138] opened 2023-04-18 08:20 UTC
I guess the image is infected by the musl/Alpine issue: https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43

See: https://www.reddit.com/r/kubernetes/comments/11kb8wy/why_i_will_never_use_alpine_linux_ever_again/

**Comment by guettli** [comment] 2023-04-18 08:26
it would be great if Alpine would fix this, but in the meantime you can use one of these images: https://github.com/lightrun-platform/koolkits

**Comment by danielloader** [comment] 2023-04-18 10:09
Doesn't seem to be, from reviewing it, servicing the same network debugging type toolkit?

**Comment by nicolaka** [comment] 2023-04-19 19:14
@guettli looks like it's been fixed in musl 1.2.4 but waiting on alpine to pick that version of musl. I'll upgrade the base image when that happens. 

https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43#note_295619

**Closed by nicolaka** 2023-04-19 19:14 UTC

**Comment by nicolaka** [comment] 2023-05-10 01:48
Fixed with v 0.11 / latest netshoot that's based on alpine 3.18 (https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43#note_306270)

**Comment by kknuut** [comment] 2025-04-10 12:35
I have still this or very similar issue in netshoot v.0.13
Local network DNS does not work, but container overlay network  and WAN side works.  For all, direct IP pings do work.

Tested pretty extensively with different host DNS and docker daemon.conf  dns settings.

Confirmed to be related to musl library by running tests on busybox:musl and busybox:glibc
musl:  Alpine 3.21.3      - Problems
glibc: Debian 12            - All tests work

+1 for rebasing to debian,  netshoot being troubleshooting container, should not have quirks on DNS.  This threw me off for quite sometime on this ocassion.
